services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  JambageCom\TslibFetce\:
    resource: '../Classes/*'

  # Register all available content objects
  JambageCom\TslibFetce\ContentObject\FormContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'FORM'


